version: '2'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/assignment
    depends_on:
      - mysql-server
    tty: true
    environment: 
        - DATABASE_HOST=mysql-server
        - DATABASE_USER=dbuser
        - DATABASE_PASSWORD=password1234
        - DATABASE_NAME=db_assignment
        - DATABASE_PORT=3306

  mysql-server:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db_assignment
      - MYSQL_PASSWORD=password1234
      - MYSQL_USER=dbuser
    volumes:
      - mysql-data-volume:/var/lib/mysql

volumes:
    mysql-data-volume:
