
logging:
    level:
        root: INFO

spring:
    profiles: container
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        initialize: true

